# Generated by Django 3.2.4 on 2021-11-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('unit', models.CharField(max_length=5, verbose_name='Unit')),
                ('quantity', models.IntegerField(default=0, max_length=10)),
                ('unit_price', models.FloatField(default=0.0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=5)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descp', models.CharField(blank=True, max_length=255)),
                ('quantity', models.FloatField(default=0.0, max_length=10)),
                ('Ingredient', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='mgr.ingredients')),
                ('menu_item', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='mgr.menuitem')),
            ],
        ),
    ]
