# Generated by Django 3.2.4 on 2021-11-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgr', '0002_auto_20211110_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='slug',
            field=models.SlugField(default='nothing', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
